name: "GoKart Scanner"
description: "Scan your Golang code for vulnerabilities with GoKart"

branding:
  icon: "check"
  color: "green"

author: "Svetlin Ralchev"

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  working_directory:
    description: "Directory to run the action on, from the repo root."
    default: '.'
  config_file:
    description: "The path to the config file."
    default: "/etc/gokart.yaml"
    required: false
  report_file:
    description: "The path to write the report."
    required: false
  report_format:
    description: "The report format (json, sarif)."
    required: false
  gokart_args:
    description: "Space seperated args specified here will be added during gokart execution."
    required: false
  github_token:
    description: "github personal access token"
    required: false

outputs:
  gokart-return-code:
    description: 'gokart command return code'
