name: "GoKart Scanner"
description: "Scan your Golang code for vulnerabilities with GoKart"

branding:
  icon: "check"
  color: "green"

author: "Svetlin Ralchev"

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  config:
    description: "input path to custom yml file"
    default: "/etc/gokart.yaml"
    required: false
  directory:
    description: "scan on a Go module in the directory"
    required: false
    default: "."
  output:
    description: "file path to write findings output"
    required: false
  globalsTainted:
    description: "marks global variables as dangerous"
    required: false
  remoteModule:
    description: "Remote gomodule to scan"
    required: false
  debug:
    description: "outputs debug logs"
    required: false
  verbose:
    description: "outputs full trace of taint analysis"
    required: false
  github_token:
    description: "github personal access token"
    required: false
